### ISSUE TITLE
amazon linux support?

### ISSUE THREAD

**Issue by charltonstanley** [dvershinin/pip-safe#6]
I tried to install pip-safe on amazon linux using the install instructions but yum reports that it can't find pip-safe. Is amazon linux supported?
Thanks in advance!

**Comment by dvershinin** [comment]
Hi, 

It's supported but no packages exist for Amazon Linux, and probably for the time being won't be available.
You can just ensure `python3` is installed (`yum install python3`), then proceed to the "other systems" installation method. For example, for global installation:

```bash
mkdir -p /opt/pip-safe
python3 -m venv /opt/pip-safe/pip-safe
/opt/pip-safe/pip-safe/bin/pip install pip-safe
ln -s /opt/pip-safe/pip-safe/bin/pip-safe /usr/local/bin/pip-safe
```

**Comment by charltonstanley** [comment]
Thank you! Is there any difference if i swap out 
`python3 -m venv /opt/pip-safe/pip-safe`
with
`/bin/virtualenv -p python3.8 /opt/pip-safe/pip-safe`
?
I ask because I'm new to venv and this is how I ended up doing it (before i saw your comment) when `virtualenv-3` didn't work for me.

**Comment by dvershinin** [comment]
I guess your way allows you to specify the exact Python version for `pip-safe` to be installed and used in the virtual environment it creates. So it's good :)

**Comment by dvershinin** [comment]
I am closing this after introducing [Amazon Linux 2 package](https://github.com/dvershinin/pip-safe#amazon-linux-2).
